server:
  port: 81
spring:
  application:
    name: springcloud-order-server
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1表示全部采集
      # 日志数据采样百分比，默认0.1(10%)，这里为了测试设置成了100%，生产环境只需要0.1即可
      probability: 1
  zipkin:
    #zipkin server的请求地址
    #    base-url: http://127.0.0.1:9411
    sender:
      ## 使用rabbitMQ进行数据传输
      type: rabbit
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      #      defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/


